name: zhongxiaozxs

on:
  workflow_dispatch:
  schedule:
    - cron: '7 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongxiaozxs
        env:
          nq9: ${{ secrets.nq9 }}
        run: |
          echo $nq9 | jq -r .zawt31 | /bin/bash
          echo $cl6590 | jq -r .xkh7 | /bin/bash

